"use client";
import './globals.css'
import NavLayout from "./nav/NavLayout";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import {ApolloProvider} from "@apollo/client";
import client from "../apollo-client";
config.autoAddCss = false;

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ApolloProvider client={client}>
            <NavLayout />
            {children}
      </ApolloProvider>
      </body>
    </html>
  )
}
